// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameAssets.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_GameAssets_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_GameAssets_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 4000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 4000000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_GameAssets_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_GameAssets_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_GameAssets_2eproto;
namespace PBTester {
class AssetBank;
class AssetBankDefaultTypeInternal;
extern AssetBankDefaultTypeInternal _AssetBank_default_instance_;
}  // namespace PBTester
PROTOBUF_NAMESPACE_OPEN
template<> ::PBTester::AssetBank* Arena::CreateMaybeMessage<::PBTester::AssetBank>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PBTester {

// ===================================================================

class AssetBank PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBTester.AssetBank) */ {
 public:
  inline AssetBank() : AssetBank(nullptr) {}
  virtual ~AssetBank();

  AssetBank(const AssetBank& from);
  AssetBank(AssetBank&& from) noexcept
    : AssetBank() {
    *this = ::std::move(from);
  }

  inline AssetBank& operator=(const AssetBank& from) {
    CopyFrom(from);
    return *this;
  }
  inline AssetBank& operator=(AssetBank&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AssetBank& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AssetBank* internal_default_instance() {
    return reinterpret_cast<const AssetBank*>(
               &_AssetBank_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AssetBank& a, AssetBank& b) {
    a.Swap(&b);
  }
  inline void Swap(AssetBank* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AssetBank* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AssetBank* New() const final {
    return CreateMaybeMessage<AssetBank>(nullptr);
  }

  AssetBank* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AssetBank>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AssetBank& from);
  void MergeFrom(const AssetBank& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AssetBank* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBTester.AssetBank";
  }
  protected:
  explicit AssetBank(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_GameAssets_2eproto);
    return ::descriptor_table_GameAssets_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHe1FieldNumber = 1,
    kHe2FieldNumber = 2,
  };
  // optional bytes he1 = 1;
  bool has_he1() const;
  private:
  bool _internal_has_he1() const;
  public:
  void clear_he1();
  const std::string& he1() const;
  void set_he1(const std::string& value);
  void set_he1(std::string&& value);
  void set_he1(const char* value);
  void set_he1(const void* value, size_t size);
  std::string* mutable_he1();
  std::string* release_he1();
  void set_allocated_he1(std::string* he1);
  private:
  const std::string& _internal_he1() const;
  void _internal_set_he1(const std::string& value);
  std::string* _internal_mutable_he1();
  public:

  // optional string he2 = 2;
  bool has_he2() const;
  private:
  bool _internal_has_he2() const;
  public:
  void clear_he2();
  const std::string& he2() const;
  void set_he2(const std::string& value);
  void set_he2(std::string&& value);
  void set_he2(const char* value);
  void set_he2(const char* value, size_t size);
  std::string* mutable_he2();
  std::string* release_he2();
  void set_allocated_he2(std::string* he2);
  private:
  const std::string& _internal_he2() const;
  void _internal_set_he2(const std::string& value);
  std::string* _internal_mutable_he2();
  public:

  // @@protoc_insertion_point(class_scope:PBTester.AssetBank)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr he1_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr he2_;
  friend struct ::TableStruct_GameAssets_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AssetBank

// optional bytes he1 = 1;
inline bool AssetBank::_internal_has_he1() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool AssetBank::has_he1() const {
  return _internal_has_he1();
}
inline void AssetBank::clear_he1() {
  he1_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& AssetBank::he1() const {
  // @@protoc_insertion_point(field_get:PBTester.AssetBank.he1)
  return _internal_he1();
}
inline void AssetBank::set_he1(const std::string& value) {
  _internal_set_he1(value);
  // @@protoc_insertion_point(field_set:PBTester.AssetBank.he1)
}
inline std::string* AssetBank::mutable_he1() {
  // @@protoc_insertion_point(field_mutable:PBTester.AssetBank.he1)
  return _internal_mutable_he1();
}
inline const std::string& AssetBank::_internal_he1() const {
  return he1_.Get();
}
inline void AssetBank::_internal_set_he1(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  he1_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void AssetBank::set_he1(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  he1_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PBTester.AssetBank.he1)
}
inline void AssetBank::set_he1(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  he1_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PBTester.AssetBank.he1)
}
inline void AssetBank::set_he1(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  he1_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PBTester.AssetBank.he1)
}
inline std::string* AssetBank::_internal_mutable_he1() {
  _has_bits_[0] |= 0x00000001u;
  return he1_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* AssetBank::release_he1() {
  // @@protoc_insertion_point(field_release:PBTester.AssetBank.he1)
  if (!_internal_has_he1()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return he1_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AssetBank::set_allocated_he1(std::string* he1) {
  if (he1 != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  he1_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), he1,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PBTester.AssetBank.he1)
}

// optional string he2 = 2;
inline bool AssetBank::_internal_has_he2() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool AssetBank::has_he2() const {
  return _internal_has_he2();
}
inline void AssetBank::clear_he2() {
  he2_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& AssetBank::he2() const {
  // @@protoc_insertion_point(field_get:PBTester.AssetBank.he2)
  return _internal_he2();
}
inline void AssetBank::set_he2(const std::string& value) {
  _internal_set_he2(value);
  // @@protoc_insertion_point(field_set:PBTester.AssetBank.he2)
}
inline std::string* AssetBank::mutable_he2() {
  // @@protoc_insertion_point(field_mutable:PBTester.AssetBank.he2)
  return _internal_mutable_he2();
}
inline const std::string& AssetBank::_internal_he2() const {
  return he2_.Get();
}
inline void AssetBank::_internal_set_he2(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  he2_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void AssetBank::set_he2(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  he2_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PBTester.AssetBank.he2)
}
inline void AssetBank::set_he2(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  he2_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PBTester.AssetBank.he2)
}
inline void AssetBank::set_he2(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  he2_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PBTester.AssetBank.he2)
}
inline std::string* AssetBank::_internal_mutable_he2() {
  _has_bits_[0] |= 0x00000002u;
  return he2_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* AssetBank::release_he2() {
  // @@protoc_insertion_point(field_release:PBTester.AssetBank.he2)
  if (!_internal_has_he2()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return he2_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AssetBank::set_allocated_he2(std::string* he2) {
  if (he2 != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  he2_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), he2,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PBTester.AssetBank.he2)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace PBTester

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_GameAssets_2eproto
